-- DATEFORMAT 이용
-- %Y :2016, %y :16 // %M : MARCH, %m : 03 // %D : 22th %d 22
SELECT ANIMAL_ID, NAME, DATE_FORMAT(DATETIME, '%Y-%m-%d') AS '날짜'
FROM ANIMAL_INS

ORDER BY ANIMAL_ID

-- left 이용
SELECT ANIMAL_ID, NAME, LEFT(DATETIME,10) AS '날짜'
FROM ANIMAL_INS

ORDER BY ANIMAL_ID