-- CASE WHEN 절
SELECT ANIMAL_TYPE, CASE WHEN NAME IS NOT NULL THEN NAME ELSE 'No name' END AS NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

-- IF 절
SELECT ANIMAL_TYPE, IF(NAME IS NULL, 'No name',NAME) AS NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID